services:
  redis:
    image: redis:7-alpine
    hostname: redis
    container_name: ems_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  web:
    build: .
    hostname: web
    container_name: ems_web
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - db_data:/app/data
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=1
    depends_on:
      - redis
    restart: unless-stopped

  celery_worker:
    build: .
    hostname: celery_worker
    container_name: ems_celery_worker
    command: celery -A core worker --loglevel=info
    volumes:
      - ./backend:/app
      - db_data:/app/data
    env_file:
      - .env
    environment:
      - DEBUG=1
    depends_on:
      - redis
    restart: unless-stopped

  flower:
    build: .
    hostname: flower
    container_name: ems_flower
    command: celery -A core flower --port=5555
    volumes:
      - ./backend:/app
      - db_data:/app/data
    ports:
      - "5555:5555"
    env_file:
      - .env
    environment:
      - DEBUG=1
    depends_on:
      - redis
      - celery_worker
    restart: unless-stopped

volumes:
  db_data: