[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["apps.employees", "apps.authentication", "apps.company", "apps.base"]
multi_line_output = 3
include_trailing_comma = true
[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
)/
'''
