# Generated by Django 5.2.5 on 2025-08-16 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='code',
            field=models.UUIDField(default=uuid.UUID('fbf61a33-d99d-4ffe-9eb9-3803a30cdefc')),
        ),
    ]
