# Generated by Django 5.2.5 on 2025-08-17 01:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_basemodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='code',
            field=models.UUIDField(default=uuid.UUID('15030634-5c27-419f-a615-70a023e847f9')),
        ),
    ]
