# Generated by Django 5.2.5 on 2025-08-17 01:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_basemodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='code',
            field=models.UUIDField(default=uuid.UUID('dbd038ba-0975-4831-8dac-12f6dbd99f47'), editable=False),
        ),
    ]
