# Generated by Django 5.2.5 on 2025-08-17 03:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_basemodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='code',
            field=models.UUIDField(default=uuid.UUID('e589d541-36b8-4db0-b144-387c0c38ac53'), editable=False),
        ),
    ]
