# Generated by Django 5.2.5 on 2025-08-17 03:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_basemodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='code',
            field=models.UUIDField(default=uuid.UUID('f7abcd10-26b8-46e9-8b41-03a291c9a395'), editable=False),
        ),
    ]
