# Generated by Django 5.2.5 on 2025-08-16 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
    ]
