# Generated by Django 5.2.5 on 2025-08-17 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_company'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.CharField(blank=True, choices=[('intern', 'Estagiário'), ('junior_dev', 'Desenvolvedor Júnior'), ('mid_dev', 'Desenvolvedor Pleno'), ('senior_dev', 'Desenvolvedor Sênior'), ('tech_lead', 'Tech Lead'), ('qa', 'Analista de QA'), ('devops', 'DevOps'), ('product_manager', 'Product Manager'), ('designer', 'Designer UX/UI'), ('cto', 'CTO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('employee', 'Employee')], max_length=8, null=True),
        ),
    ]
