# Generated by Django 5.2.5 on 2025-08-16 15:34

import apps.company.models.validators.validate_cep
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('name', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=8, validators=[apps.company.models.validators.validate_cep.validate_cep])),
            ],
            bases=('base.basemodel',),
        ),
    ]
